
version: "3.9"

services:
  pgop:
    build: .
    container_name: pgop_app
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    environment:
      - STREAMLIT_SERVER_PORT=8501
    restart: unless-stopped
